from django.urls import path

from .views import (
    BrandView,
    ClassCancelView,
    ClassCompleteView,
    ClassDetailView,
    ClassListCreateView,
    CompleteOnboardingView,
    GoogleCallbackView,
    GoogleConnectView,
    GoogleDisconnectView,
    GoogleQuickMeetLinkView,
    GoogleStatusView,
    InvoiceDetailView,
    InvoiceListCreateView,
    LoginView,
    LogoutView,
    MaterialDetailView,
    MaterialListCreateView,
    MonthlyReportDownloadView,
    OtpRequestView,
    OtpVerifyView,
    ParentDashboardView,
    ParentInvoicesView,
    ParentLookupView,
    ParentProgressView,
    ParentReportsView,
    ParentStudentsView,
    PasswordResetConfirmView,
    PasswordResetRequestView,
    QuizDetailView,
    QuizListCreateView,
    RecordPaymentView,
    SignupView,
    StudentListCreateView,
)

# Paths match frontend/src/lib/api.js exactly — keep the two in sync.
# students/<id>/complete-onboarding/ matches ../whatsapp/app/conversation.py's
# _notify_backend_complete — keep those two in sync as well.
urlpatterns = [
    path('auth/signup/', SignupView.as_view(), name='auth-signup'),
    path('auth/login/', LoginView.as_view(), name='auth-login'),
    path('auth/logout/', LogoutView.as_view(), name='auth-logout'),
    path('auth/otp/request/', OtpRequestView.as_view(), name='auth-otp-request'),
    path('auth/otp/verify/', OtpVerifyView.as_view(), name='auth-otp-verify'),
    path('auth/password-reset/request/', PasswordResetRequestView.as_view(), name='auth-password-reset-request'),
    path('auth/password-reset/confirm/', PasswordResetConfirmView.as_view(), name='auth-password-reset-confirm'),
    path('students/', StudentListCreateView.as_view(), name='students'),
    path('students/<uuid:student_id>/complete-onboarding/', CompleteOnboardingView.as_view(), name='complete-onboarding'),
    path('classes/', ClassListCreateView.as_view(), name='classes'),
    path('classes/<uuid:class_id>/', ClassDetailView.as_view(), name='class-detail'),
    path('classes/<uuid:class_id>/cancel/', ClassCancelView.as_view(), name='class-cancel'),
    path('classes/<uuid:class_id>/complete/', ClassCompleteView.as_view(), name='class-complete'),
    path('google/connect/', GoogleConnectView.as_view(), name='google-connect'),
    path('google/callback/', GoogleCallbackView.as_view(), name='google-callback'),
    path('google/status/', GoogleStatusView.as_view(), name='google-status'),
    path('google/disconnect/', GoogleDisconnectView.as_view(), name='google-disconnect'),
    path('google/meet-link/', GoogleQuickMeetLinkView.as_view(), name='google-meet-link'),
    path('brand/', BrandView.as_view(), name='brand'),
    path('invoices/', InvoiceListCreateView.as_view(), name='invoices'),
    path('invoices/<uuid:invoice_id>/', InvoiceDetailView.as_view(), name='invoice-detail'),
    path('invoices/<uuid:invoice_id>/payments/', RecordPaymentView.as_view(), name='invoice-payments'),
    path('materials/', MaterialListCreateView.as_view(), name='materials'),
    path('materials/<uuid:material_id>/', MaterialDetailView.as_view(), name='material-detail'),
    path('quizzes/', QuizListCreateView.as_view(), name='quizzes'),
    path('quizzes/<uuid:quiz_id>/', QuizDetailView.as_view(), name='quiz-detail'),
    path('reports/monthly/<str:token>/', MonthlyReportDownloadView.as_view(), name='monthly-report-download'),
    path('whatsapp/parent-lookup/', ParentLookupView.as_view(), name='whatsapp-parent-lookup'),
    path('parent/students/', ParentStudentsView.as_view(), name='parent-students'),
    path('parent/dashboard/', ParentDashboardView.as_view(), name='parent-dashboard'),
    path('parent/progress/', ParentProgressView.as_view(), name='parent-progress'),
    path('parent/reports/', ParentReportsView.as_view(), name='parent-reports'),
    path('parent/invoices/', ParentInvoicesView.as_view(), name='parent-invoices'),
]
