/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "paper-300": "#CFCABB",
        "inverse-on-surface": "#f2f1ed",
        "success-solid": "#2E7D5B",
        "on-primary-fixed": "#00201c",
        "ink-700": "#3A4441",
        "surface-container-highest": "#e3e2df",
        "surface-container-lowest": "#ffffff",
        "background": "#faf9f5",
        "primary": "#005248",
        "on-error-container": "#93000a",
        "inverse-primary": "#8bd4c6",
        "on-secondary-fixed": "#2a1800",
        "surface-dim": "#dbdad6",
        "paper-0": "#FFFFFF",
        "danger-tint": "#F7E1DC",
        "on-tertiary": "#ffffff",
        "paper-200": "#E5E2D8",
        "secondary-container": "#ffb54f",
        "tertiary-fixed": "#c5eae4",
        "on-primary-fixed-variant": "#005047",
        "paper-100": "#F1EFE8",
        "warning-tint": "#F8ECD3",
        "on-secondary-container": "#724700",
        "on-primary": "#ffffff",
        "surface-bright": "#faf9f5",
        "ink-500": "#6A716C",
        "tertiary": "#2c4e49",
        "secondary": "#845400",
        "on-secondary-fixed-variant": "#643f00",
        "on-secondary": "#ffffff",
        "on-surface": "#1b1c1a",
        "on-background": "#1b1c1a",
        "error": "#ba1a1a",
        "on-primary-container": "#9fe9da",
        "primary-container": "#1c6b60",
        "outline-variant": "#bec9c5",
        "surface-container-low": "#f4f4f0",
        "on-surface-variant": "#3f4946",
        "surface-container": "#efeeea",
        "on-tertiary-container": "#bde2dc",
        "secondary-fixed-dim": "#ffb95b",
        "primary-fixed": "#a7f0e2",
        "surface-tint": "#1a6a5f",
        "on-tertiary-fixed": "#00201d",
        "surface-container-high": "#e9e8e4",
        "tertiary-fixed-dim": "#a9cec8",
        "primary-fixed-dim": "#8bd4c6",
        "tertiary-container": "#446661",
        "warning-solid": "#B9791A",
        "success-tint": "#E2F0E9",
        "ink-900": "#16211E",
        "on-error": "#ffffff",
        "surface-variant": "#e3e2df",
        "on-tertiary-fixed-variant": "#2b4d48",
        "danger-solid": "#BE3F2C",
        "surface": "#faf9f5",
        "secondary-fixed": "#ffddb6",
        "inverse-surface": "#2f312e",
        "error-container": "#ffdad6",
        "outline": "#6f7976",
        /* Extra utility colors for glass effects */
        "glass-white": "rgba(255, 255, 255, 0.72)",
        "glass-border": "rgba(255, 255, 255, 0.18)",
      },
      "borderRadius": {
        "DEFAULT": "0.375rem",
        "lg": "0.625rem",
        "xl": "0.875rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "4px",
        "space-0.5": "2px",
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-5": "20px",
        "space-6": "24px",
        "space-8": "32px",
        "space-10": "40px",
        "space-12": "48px",
        "gutter-desktop": "28px",
        "gutter-mobile": "16px",
        "max-width": "1280px"
      },
      /* Refined type scale — tighter, more premium feel */
      "fontFamily": {
        "display-lg": ["'DM Sans'", "Inter", "system-ui", "sans-serif"],
        "display-md": ["'DM Sans'", "Inter", "system-ui", "sans-serif"],
        "title-lg":   ["'DM Sans'", "Inter", "system-ui", "sans-serif"],
        "title-md":   ["Inter", "'DM Sans'", "system-ui", "sans-serif"],
        "title-sm":   ["Inter", "'DM Sans'", "system-ui", "sans-serif"],
        "label":      ["Inter", "'DM Sans'", "system-ui", "sans-serif"],
        "body":       ["Inter", "'DM Sans'", "system-ui", "sans-serif"],
        "body-lg":    ["Inter", "'DM Sans'", "system-ui", "sans-serif"],
        "caption":    ["Inter", "'DM Sans'", "system-ui", "sans-serif"],
        "data-display": ["'IBM Plex Mono'", "monospace"],
      },
      "fontSize": {
        "display-lg": ["28px", { "lineHeight": "34px", "fontWeight": "700", "letterSpacing": "-0.02em" }],
        "display-md": ["24px", { "lineHeight": "30px", "fontWeight": "700", "letterSpacing": "-0.015em" }],
        "title-lg":   ["18px", { "lineHeight": "24px", "fontWeight": "600", "letterSpacing": "-0.01em" }],
        "title-md":   ["15px", { "lineHeight": "21px", "fontWeight": "600", "letterSpacing": "-0.005em" }],
        "title-sm":   ["13.5px", { "lineHeight": "19px", "fontWeight": "600" }],
        "label":      ["12px", { "lineHeight": "16px", "fontWeight": "500", "letterSpacing": "0.01em" }],
        "body":       ["13.5px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg":    ["14.5px", { "lineHeight": "22px", "fontWeight": "400" }],
        "caption":    ["11px", { "lineHeight": "15px", "fontWeight": "500", "letterSpacing": "0.015em" }],
        "data-display": ["13px", { "lineHeight": "20px", "fontWeight": "500" }],
      },
      boxShadow: {
        "card":       "0 1px 3px rgba(22, 33, 30, 0.04), 0 1px 2px rgba(22, 33, 30, 0.06)",
        "card-hover": "0 4px 16px rgba(22, 33, 30, 0.08), 0 2px 6px rgba(22, 33, 30, 0.04)",
        "elevated":   "0 8px 30px rgba(22, 33, 30, 0.10), 0 2px 8px rgba(22, 33, 30, 0.06)",
        "glass":      "0 8px 32px rgba(22, 33, 30, 0.06)",
        "inner-glow": "inset 0 1px 0 rgba(255, 255, 255, 0.1)",
      },
      backdropBlur: {
        "glass": "16px",
      },
      keyframes: {
        "fade-in": {
          "0%":   { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%":   { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%":   { opacity: "0", transform: "translateX(12px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          "0%":   { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%":      { opacity: "0.6" },
        },
        "shimmer": {
          "0%":   { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "fade-in":       "fade-in 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in-up":    "fade-in-up 0.45s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-in-right":"slide-in-right 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "scale-in":      "scale-in 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "pulse-soft":    "pulse-soft 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "shimmer":       "shimmer 2s linear infinite",
      },
      transitionTimingFunction: {
        "spring": "cubic-bezier(0.16, 1, 0.3, 1)",
      },
    }
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms')
  ],
}
