# Generated by Django 5.1.4 on 2026-09-29 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_loginotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="attendance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("late", "Late"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="classsession",
            name="cancel_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="classsession",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="classsession",
            name="google_task_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="classsession",
            name="homework_due_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classsession",
            name="session_notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_email", models.EmailField(blank=True, max_length=254)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expires_at", models.DateTimeField()),
                ("scope", models.TextField(blank=True)),
                ("calendar_sync_token", models.TextField(blank=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tutor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
