# Generated by Django 5.1.4 on 2026-09-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_classsession_attendance_classsession_cancel_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classsession",
            name="reminder_1h_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="classsession",
            name="reminder_24h_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="last_report_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
