# Generated by Django 5.1.4 on 2026-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_classsession_reminder_1h_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="payment_instructions",
            field=models.TextField(blank=True),
        ),
    ]
