# Generated by Django 5.1.4 on 2026-09-30 09:34

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_payment_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleaccount",
            name="access_token",
            field=core.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="googleaccount",
            name="refresh_token",
            field=core.fields.EncryptedTextField(),
        ),
    ]
